# Generated by Django 5.2.5 on 2025-11-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_perfilusuario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['numero'], 'permissions': [('can_change_room_state', 'Can change room state')], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva'], 'permissions': [('can_confirm_reservation', 'Can confirm reservation'), ('can_cancel_reservation', 'Can cancel reservation')], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hotel.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_huespedes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='precio_por_noche',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['numero'], name='hotel_habit_numero_452b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['estado'], name='hotel_habit_estado_9b2882_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['cedula'], name='hotel_perfi_cedula_fc1353_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['habitacion', 'fecha_entrada', 'fecha_salida'], name='hotel_reser_habitac_9e00d3_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='hotel_reser_estado_b95b96_idx'),
        ),
        migrations.AddIndex(
            model_name='tipohabitacion',
            index=models.Index(fields=['nombre'], name='hotel_tipoh_nombre_2e28fb_idx'),
        ),
    ]
